# create your drupal and postgres config here, based off the last assignment
services:
  drupal:
    build:
      context: .
      dockerfile: Dockerfile
    image: custom-drupal-check
    ports:
      - "80:80"
    depends_on:
      - postgress
    environment:
      DRUPAL_DB_HOST: postgress
      DRUPAL_DB_USER: postgress
      DRUPAL_DB_PASSWORD: mysecretpassword
      DRUPAL_DB_NAME: postgress
    volumes:
      - drupal-data:/var/www/html/


  postgress:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - postgress-data:/var/lib/postgresql/data

volumes:
  drupal-data:
  postgress-data:
